name: Continuous Integration

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta Setup
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # minimal
            type=semver,pattern={{version}}
      - name: Test
        run: |
          ./testImage.sh ${{ env.IMAGE_NAME }}
