name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

env:
  IMAGE_NAME: dylanowen/wasm-pack

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Make sure we get all our tags
          token: ${{ secrets.PAT }} # Run our git interactions as a real user

      - name: Docker meta Setup
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Test
        run: |
          ./testImage.sh ${{ env.IMAGE_NAME }}

      - name: Tag Main
        if: github.ref == 'refs/heads/main'
        run: |
          ./createTag.sh
