name: Continuous Integration

on: [ push, pull_request ]

env:
  IMAGE_NAME: dylanowen/wasm-pack

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta Setup
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Test
        run: |
          ./testImage.sh ${{ env.IMAGE_NAME }}

      - name: Tag Main
        if: github.ref == 'refs/heads/main'
        run: |
          ./createTag.sh
