name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  IMAGE_NAME: dylanowen/wasm-pack

jobs:
  ensure_main:
    name: Ensure Main Branch
    runs-on: ubuntu-latest
    outputs:
      is_main: ${{ steps.is_main.outputs.is_main }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Make sure we get all our tags

      - name: Is Main
        id: is_main
        run: |
          echo "Tags on main (looking for ${{ github.ref_name }}):"
          git tag --merged origin/main
          if git tag --merged origin/main 2>/dev/null | grep -q '${{ github.ref_name }}' ; then
            echo "Our tag IS on the main branch"
            echo "is_main=true" >> $GITHUB_OUTPUT
          else
            echo "Our tag IS NOT the main branch"
            echo "is_main=false" >> $GITHUB_OUTPUT
          fi

  build_amd64:
    name: Build for AMD64
    runs-on: ubuntu-latest
    needs: ensure_main
    if: needs.ensure_main.outputs.is_main == 'true'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_arm64:
    name: Build For Arm64
    runs-on: ubuntu-latest
    needs: ensure_main
    if: needs.ensure_main.outputs.is_main == 'true'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
