name: Update Image

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Latest Stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal # we just need rustc to get the version
      - name: Check Version
        run: |
          rustc --version
