name: Auto Update

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Auto Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Image
        run: |
          ./updateImage.sh
          echo "VERSION_TAG=$(head -1 Dockerfile | cut -d ':' -f 2)" >> $GITHUB_ENV

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }} # Trigger our PR as a real user
          title: ${{ format('Update to Rust {0}', env.VERSION_TAG) }}
          branch: ${{ format('auto-update-{0}', env.VERSION_TAG) }}
          labels: |
            auto-update
          delete-branch: true

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
